// <auto-generated />
using Ap.Demo.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ap.Demo.Infrastructure.Migrations
{
    [DbContext(typeof(MyCitiesContext))]
    partial class MyCitiesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ap.Demo.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("tblCities", "City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Antwerpen",
                            Population = 530000
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Gent",
                            Population = 260000
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Amsterdam",
                            Population = 820000
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 3,
                            Name = "Parijs",
                            Population = 2140000
                        });
                });

            modelBuilder.Entity("Ap.Demo.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblCountries", "Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "België"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nederland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Frankrijk"
                        });
                });

            modelBuilder.Entity("Ap.Demo.Domain.City", b =>
                {
                    b.HasOne("Ap.Demo.Domain.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Ap.Demo.Domain.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
